version: '2'
services:
  alesia-app:
    image: pingouinfinihub/alesia:latest
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://alesia-postgresql:5432/Alesia
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
    ports:
      - 28081:28080
  alesia-postgresql:
    extends:
      file: postgresql.yml
      service: alesia-postgresql
